"""Integracao de analises

Revision ID: e4843bb0189c
Revises: be51c908c330
Create Date: 2026-05-24 17:31:52.126104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4843bb0189c'
down_revision = 'be51c908c330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['login_id'], ['login.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_login_id'), ['login_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('conversation_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=10), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_analysis_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index('ix_conversation_analysis_conversation_computed', ['conversation_id', 'computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_analysis_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_analysis_conversation_id'))
        batch_op.drop_index('ix_conversation_analysis_conversation_computed')
        batch_op.drop_index(batch_op.f('ix_conversation_analysis_computed_at'))

    op.drop_table('conversation_analysis')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_login_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
